# Copyright (C) 2013 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/mint/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/mint/proprietary/bin/at_distributor:system/bin/at_distributor \
    vendor/samsung/mint/proprietary/bin/bluetoothd:system/bin/bluetoothd \
    vendor/samsung/mint/proprietary/bin/engappclient:system/bin/engappclient \
    vendor/samsung/mint/proprietary/bin/engmodemclient:system/bin/engmodemclient \
    vendor/samsung/mint/proprietary/bin/engpcclient:system/bin/engpcclient \
    vendor/samsung/mint/proprietary/bin/engservice:system/bin/engservice \
    vendor/samsung/mint/proprietary/bin/engsetmacaddr:system/bin/engsetmacaddr \
    vendor/samsung/mint/proprietary/bin/immvibed:system/bin/immvibed \
    vendor/samsung/mint/proprietary/bin/macloader:system/bin/macloader \
    vendor/samsung/mint/proprietary/bin/nvm_daemon:system/bin/nvm_daemon \
    vendor/samsung/mint/proprietary/bin/slog:system/bin/slog \
    vendor/samsung/mint/proprietary/bin/slogctl:system/bin/slogctl \
    vendor/samsung/mint/proprietary/bin/sprd_monitor:system/bin/sprd_monitor \
    vendor/samsung/mint/proprietary/bin/tar:system/bin/tar \
    vendor/samsung/mint/proprietary/bin/rild_sp:system/bin/rild_sp \
    vendor/samsung/mint/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/samsung/mint/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so \
    vendor/samsung/mint/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
    vendor/samsung/mint/proprietary/lib/libomission_avoidance.so:system/lib/libomission_avoidance.so \
    vendor/samsung/mint/proprietary/lib/libfactoryutil.so:system/lib/libfactoryutil.so \
    vendor/samsung/mint/proprietary/bin/phoneserver:system/bin/phoneserver \
    vendor/samsung/mint/proprietary/bin/phoneserver_2sim:system/bin/phoneserver_2sim \
    vendor/samsung/mint/proprietary/etc/DiamondVoice.txt:system/etc/DiamondVoice.txt \
    vendor/samsung/mint/proprietary/lib/modules/VoiceSolution.ko:system/lib/modules/VoiceSolution.ko \
    vendor/samsung/mint/proprietary/bin/bcm4330.hcd:system/bin/bcm4330.hcd \
    vendor/samsung/mint/proprietary/etc/wifi/bcmdhd_apsta.bin:system/etc/wifi/bcmdhd_apsta.bin \
    vendor/samsung/mint/proprietary/etc/wifi/bcmdhd_mfg.bin:system/etc/wifi/bcmdhd_mfg.bin \
    vendor/samsung/mint/proprietary/etc/wifi/bcmdhd_p2p.bin:system/etc/wifi/bcmdhd_p2p.bin \
    vendor/samsung/mint/proprietary/etc/wifi/bcmdhd_sta.bin:system/etc/wifi/bcmdhd_sta.bin \
    vendor/samsung/mint/proprietary/etc/wifi/nvram_mfg.txt:system/etc/wifi/nvram_mfg.txt \
    vendor/samsung/mint/proprietary/etc/wifi/nvram_net.txt:system/etc/wifi/nvram_net.txt \
    vendor/samsung/mint/proprietary/etc/wifi/wpa_supplicant.conf:system/etc/wifi/wpa_supplicant.conf \
    vendor/samsung/mint/proprietary/vendor/firmware/fw_bcmdhd.bin:system/vendor/firmware/fw_bcmdhd.bin \
    vendor/samsung/mint/proprietary/vendor/firmware/fw_bcmdhd_apsta.bin:system/vendor/firmware/fw_bcmdhd_apsta.bin \
    vendor/samsung/mint/proprietary/vendor/firmware/fw_bcmdhd_p2p.bin:system/vendor/firmware/fw_bcmdhd_p2p.bin \
    vendor/samsung/mint/proprietary/bin/ss_daemon:system/bin/ss_daemon \
    vendor/samsung/mint/proprietary/lib/hw/gralloc.sc8810.so:system/lib/hw/gralloc.sc8810.so \
    vendor/samsung/mint/proprietary/lib/egl/libEGL_mali.so:system/lib/egl/libEGL_mali.so \
    vendor/samsung/mint/proprietary/lib/egl/libGLESv2_mali.so:system/lib/egl/libGLESv2_mali.so \
    vendor/samsung/mint/proprietary/lib/egl/libGLESv1_CM_mali.so:system/lib/egl/libGLESv1_CM_mali.so \
    vendor/samsung/mint/proprietary/lib/libMali.so:system/lib/libMali.so \
    vendor/samsung/mint/proprietary/lib/libUMP.so:system/lib/libUMP.so \
    vendor/samsung/mint/proprietary/etc/Volume.db:system/etc/Volume.db \
    vendor/samsung/mint/proprietary/lib/hw/audio.primary.sc8810.so:system/lib/hw/audio.primary.sc8810.so \
    vendor/samsung/mint/proprietary/lib/hw/audio_policy.sc8810.so:system/lib/hw/audio_policy.sc8810.so \
    vendor/samsung/mint/proprietary/lib/libaudiopolicy_sec.so:system/lib/libaudiopolicy_sec.so \
    vendor/samsung/mint/proprietary/lib/libcontrolcsc.so:system/lib/libcontrolcsc.so \
    vendor/samsung/mint/proprietary/lib/libLifevibes_lvvefs.so:system/lib/libLifevibes_lvvefs.so \
    vendor/samsung/mint/proprietary/lib/liblvvewrapper.so:system/lib/liblvvewrapper.so \
    vendor/samsung/mint/proprietary/lib/libsamsungSoundbooster.so:system/lib/libsamsungSoundbooster.so \
    vendor/samsung/mint/proprietary/lib/libsamsungRecord.so:system/lib/libsamsungRecord.so \
    vendor/samsung/mint/proprietary/lib/lib_SamsungRec_V02002.so:system/lib/lib_SamsungRec_V02002.so \
    vendor/samsung/mint/proprietary/lib/lib_Samsung_Resampler.so:system/lib/lib_Samsung_Resampler.so \
    vendor/samsung/mint/proprietary/lib/lib_Samsung_SB_AM_for_ICS_v03008.so:system/lib/lib_Samsung_SB_AM_for_ICS_v03008.so \
    vendor/samsung/mint/proprietary/lib/libvbeffect.so:system/lib/libvbeffect.so \
    vendor/samsung/mint/proprietary/lib/libvbpga.so:system/lib/libvbpga.so \
    vendor/samsung/mint/proprietary/lib/libvolumemanager.so:system/lib/libvolumemanager.so \
    vendor/samsung/mint/proprietary/lib/libxlist.so:system/lib/libxlist.so \
    vendor/samsung/mint/proprietary/etc/audio/LVVEFS_Rx_Configuration.txt:system/etc/audio/LVVEFS_Rx_Configuration.txt \
    vendor/samsung/mint/proprietary/etc/audio/LVVEFS_Tx_Configuration.txt:system/etc/audio/LVVEFS_Tx_Configuration.txt \
    vendor/samsung/mint/proprietary/etc/audio/Rx_ControlParams_BLUETOOTH_HEADSET.txt:system/etc/audio/Rx_ControlParams_BLUETOOTH_HEADSET.txt \
    vendor/samsung/mint/proprietary/etc/audio/Rx_ControlParams_EARPIECE_WIDEBAND.txt:system/etc/audio/Rx_ControlParams_EARPIECE_WIDEBAND.txt \
    vendor/samsung/mint/proprietary/etc/audio/Rx_ControlParams_SPEAKER_WIDEBAND.txt:system/etc/audio/Rx_ControlParams_SPEAKER_WIDEBAND.txt \
    vendor/samsung/mint/proprietary/etc/audio/Rx_ControlParams_WIRED_HEADPHONE_WIDEBAND.txt:system/etc/audio/Rx_ControlParams_WIRED_HEADPHONE_WIDEBAND.txt \
    vendor/samsung/mint/proprietary/etc/audio/Rx_ControlParams_WIRED_HEADSET_WIDEBAND.txt:system/etc/audio/Rx_ControlParams_WIRED_HEADSET_WIDEBAND.txt \
    vendor/samsung/mint/proprietary/etc/audio/Tx_ControlParams_BLUETOOTH_HEADSET.txt:system/etc/audio/Tx_ControlParams_BLUETOOTH_HEADSET.txt \
    vendor/samsung/mint/proprietary/etc/audio/Tx_ControlParams_EARPIECE_WIDEBAND.txt:system/etc/audio/Tx_ControlParams_EARPIECE_WIDEBAND.txt \
    vendor/samsung/mint/proprietary/etc/audio/Tx_ControlParams_SPEAKER_WIDEBAND.txt:system/etc/audio/Tx_ControlParams_SPEAKER_WIDEBAND.txt \
    vendor/samsung/mint/proprietary/etc/audio/Tx_ControlParams_WIRED_HEADPHONE_WIDEBAND.txt:system/etc/audio/Tx_ControlParams_WIRED_HEADPHONE_WIDEBAND.txt \
    vendor/samsung/mint/proprietary/etc/audio/Tx_ControlParams_WIRED_HEADSET_WIDEBAND.txt:system/etc/audio/Tx_ControlParams_WIRED_HEADSET_WIDEBAND.txt \
    vendor/samsung/mint/proprietary/etc/audio_VR/LVVEFS_Rx_Configuration.txt:system/etc/audio_VR/LVVEFS_Rx_Configuration.txt \
    vendor/samsung/mint/proprietary/etc/audio_VR/LVVEFS_Tx_Configuration.txt:system/etc/audio_VR/LVVEFS_Tx_Configuration.txt \
    vendor/samsung/mint/proprietary/etc/audio_VR/Rx_ControlParams_VR_BLUETOOTH_HEADSET.txt:system/etc/audio_VR/Rx_ControlParams_VR_BLUETOOTH_HEADSET.txt \
    vendor/samsung/mint/proprietary/etc/audio_VR/Rx_ControlParams_VR_EARPIECE_WIDEBAND.txt:system/etc/audio_VR/Rx_ControlParams_VR_EARPIECE_WIDEBAND.txt \
    vendor/samsung/mint/proprietary/etc/audio_VR/Rx_ControlParams_VR_SPEAKER_WIDEBAND.txt:system/etc/audio_VR/Rx_ControlParams_VR_SPEAKER_WIDEBAND.txt \
    vendor/samsung/mint/proprietary/etc/audio_VR/Rx_ControlParams_VR_WIRED_HEADPHONE_WIDEBAND.txt:system/etc/audio_VR/Rx_ControlParams_VR_WIRED_HEADPHONE_WIDEBAND.txt \
    vendor/samsung/mint/proprietary/etc/audio_VR/Rx_ControlParams_VR_WIRED_HEADSET_WIDEBAND.txt:system/etc/audio_VR/Rx_ControlParams_VR_WIRED_HEADSET_WIDEBAND.txt \
    vendor/samsung/mint/proprietary/etc/audio_VR/Tx_ControlParams_VR_BLUETOOTH_HEADSET.txt:system/etc/audio_VR/Tx_ControlParams_VR_BLUETOOTH_HEADSET.txt \
    vendor/samsung/mint/proprietary/etc/audio_VR/Tx_ControlParams_VR_EARPIECE_WIDEBAND.txt:system/etc/audio_VR/Tx_ControlParams_VR_EARPIECE_WIDEBAND.txt \
    vendor/samsung/mint/proprietary/etc/audio_VR/Tx_ControlParams_VR_SPEAKER_WIDEBAND.txt:system/etc/audio_VR/Tx_ControlParams_VR_SPEAKER_WIDEBAND.txt \
    vendor/samsung/mint/proprietary/etc/audio_VR/Tx_ControlParams_VR_WIRED_HEADPHONE_WIDEBAND.txt:system/etc/audio_VR/Tx_ControlParams_VR_WIRED_HEADPHONE_WIDEBAND.txt \
    vendor/samsung/mint/proprietary/etc/audio_VR/Tx_ControlParams_VR_WIRED_HEADSET_WIDEBAND.txt:system/etc/audio_VR/Tx_ControlParams_VR_WIRED_HEADSET_WIDEBAND.txt \
    vendor/samsung/mint/proprietary/etc/pvplayer.cfg:system/etc/pvplayer.cfg \
    vendor/samsung/mint/proprietary/lib/libomx_avcdec_sharedlibrary.so:system/lib/libomx_avcdec_sharedlibrary.so \
    vendor/samsung/mint/proprietary/lib/libomx_m4vdec_sharedlibrary.so:system/lib/libomx_m4vdec_sharedlibrary.so \
    vendor/samsung/mint/proprietary/lib/libomx_m4venc_sharedlibrary.so:system/lib/libomx_m4venc_sharedlibrary.so \
    vendor/samsung/mint/proprietary/lib/libomx_sharedlibrary.so:system/lib/libomx_sharedlibrary.so \
    vendor/samsung/mint/proprietary/lib/libopencore_common.so:system/lib/libopencore_common.so \
    vendor/samsung/mint/proprietary/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \
    vendor/samsung/mint/proprietary/lib/libstagefright_soft_h264dec_sprd.so:system/lib/libstagefright_soft_h264dec_sprd.so \
    vendor/samsung/mint/proprietary/lib/libstagefright_soft_mpeg4dec_sprd.so:system/lib/libstagefright_soft_mpeg4dec_sprd.so \
    vendor/samsung/mint/proprietary/bin/ext_data.sh:system/bin/ext_data.sh \
    vendor/samsung/mint/proprietary/bin/ext_kill.sh:system/bin/ext_kill.sh \
    vendor/samsung/mint/proprietary/bin/ext_symlink.sh:system/bin/ext_symlink.sh \
    vendor/samsung/mint/proprietary/etc/slog.conf.user:system/etc/slog.conf.user \
    vendor/samsung/mint/proprietary/etc/slog.conf:system/etc/slog.conf \
    vendor/samsung/mint/proprietary/lib/libatparser.so:system/lib/libatparser.so \
    vendor/samsung/mint/proprietary/lib/libeng_wifi_ptest.so:system/lib/libeng_wifi_ptest.so \
    vendor/samsung/mint/proprietary/lib/libengclient.so:system/lib/libengclient.so \
    vendor/samsung/mint/proprietary/lib/libnvaccessor.so:system/lib/libnvaccessor.so \
    vendor/samsung/mint/proprietary/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
    vendor/samsung/mint/proprietary/lib/libwvdrm_L3.so:system/lib/libwvdrm_L3.so \
    vendor/samsung/mint/proprietary/lib/libwvm.so:system/lib/libwvm.so \
    vendor/samsung/mint/proprietary/lib/libWVStreamControlAPI_L3.so:system/lib/libWVStreamControlAPI_L3.so
